#!/bin/bash
#
# This script can only be run from the computer on which it was
# originally downloaded.
#
# This auto-generated script was downloaded from http://iotta.snia.org.
# It will download the 153 subtraces of 8r
#
echo "Downloading the 153 subtraces of 8r" 1>&2
cookies=$(mktemp)
cat >> $cookies << 'EOF'
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by iotta.snia.org! Edit at your own risk.

.iotta.snia.org	TRUE	/	FALSE	0	infodigest	dfaa5ee7dc27c0e4839565e9aee308f74bb6c8b1
.iotta.snia.org	TRUE	/	FALSE	0	legal	true
.iotta.snia.org	TRUE	/	FALSE	0	id	598409
EOF

if which wget >/dev/null 2>&1; then
  useWGET=true
elif which curl >/dev/null 2>&1; then
  useCURL=true
else
  echo "Couldn't find either wget or curl. Please install one of them" 1>&2
  exit 1
fi

checkForError() {
  delete=false
  if $useWGET && (( $1 == 2 || $1 == 3 || $1 == 5 || $1 == 7 || $1 == 8 ))
  then
    delete=true
  elif $useWGET && [ ! -s "$2" ]
  then
    delete=true
  elif $useCURL && (( $1 == 22 || $1 == 36 ))
  then
    delete=true
  fi
}

downloadFile() {
  file=$1
  id=$2
  url="http://server2.iotta.snia.org/traces/$id/download?type=file&sType="
  if $useWGET; then
    wget -q --load-cookies=$cookies -O "$file" -c "$url""wget"
  elif $useCURL; then
    curl -s -f -b $cookies -o "$file" -C - -L "$url""curl"
  fi

  if [ $? -eq 0 ]; then
    echo "Finished Downloading $file"
  else 
    checkForError $? "$file"
    if $delete; then
      echo "There was an error downloading the file ($file)"
      rm -f "$file"
    else
      echo "$file was partially downloaded"
    fi
    echo "Stopping..."
    exit 1
  fi
}

downloadFile "ubc-dedup-8r-000.tar" 3889
downloadFile "ubc-dedup-8r-001.tar" 3890
downloadFile "ubc-dedup-8r-002.tar" 3891
downloadFile "ubc-dedup-8r-003.tar" 3892
downloadFile "ubc-dedup-8r-004.tar" 3893
downloadFile "ubc-dedup-8r-005.tar" 3894
downloadFile "ubc-dedup-8r-006.tar" 3895
downloadFile "ubc-dedup-8r-007.tar" 3896
downloadFile "ubc-dedup-8r-008.tar" 3897
downloadFile "ubc-dedup-8r-009.tar" 3898
downloadFile "ubc-dedup-8r-010.tar" 3899
downloadFile "ubc-dedup-8r-011.tar" 3900
downloadFile "ubc-dedup-8r-012.tar" 3901
downloadFile "ubc-dedup-8r-013.tar" 3902
downloadFile "ubc-dedup-8r-014.tar" 3903
downloadFile "ubc-dedup-8r-015.tar" 3904
downloadFile "ubc-dedup-8r-016.tar" 3905
downloadFile "ubc-dedup-8r-017.tar" 3906
downloadFile "ubc-dedup-8r-018.tar" 3907
downloadFile "ubc-dedup-8r-019.tar" 3908
downloadFile "ubc-dedup-8r-020.tar" 3909
downloadFile "ubc-dedup-8r-021.tar" 3910
downloadFile "ubc-dedup-8r-022.tar" 3911
downloadFile "ubc-dedup-8r-023.tar" 3912
downloadFile "ubc-dedup-8r-024.tar" 3913
downloadFile "ubc-dedup-8r-025.tar" 3914
downloadFile "ubc-dedup-8r-026.tar" 3915
downloadFile "ubc-dedup-8r-027.tar" 3916
downloadFile "ubc-dedup-8r-028.tar" 3917
downloadFile "ubc-dedup-8r-029.tar" 3918
downloadFile "ubc-dedup-8r-030.tar" 3919
downloadFile "ubc-dedup-8r-031.tar" 3920
downloadFile "ubc-dedup-8r-032.tar" 3921
downloadFile "ubc-dedup-8r-033.tar" 3922
downloadFile "ubc-dedup-8r-034.tar" 3923
downloadFile "ubc-dedup-8r-035.tar" 3924
downloadFile "ubc-dedup-8r-036.tar" 3925
downloadFile "ubc-dedup-8r-037.tar" 3926
downloadFile "ubc-dedup-8r-038.tar" 3927
downloadFile "ubc-dedup-8r-039.tar" 3928
downloadFile "ubc-dedup-8r-040.tar" 3929
downloadFile "ubc-dedup-8r-041.tar" 3930
downloadFile "ubc-dedup-8r-042.tar" 3931
downloadFile "ubc-dedup-8r-043.tar" 3932
downloadFile "ubc-dedup-8r-044.tar" 3933
downloadFile "ubc-dedup-8r-045.tar" 3934
downloadFile "ubc-dedup-8r-046.tar" 3935
downloadFile "ubc-dedup-8r-047.tar" 3936
downloadFile "ubc-dedup-8r-048.tar" 3937
downloadFile "ubc-dedup-8r-049.tar" 3938
downloadFile "ubc-dedup-8r-050.tar" 3939
downloadFile "ubc-dedup-8r-051.tar" 3940
downloadFile "ubc-dedup-8r-052.tar" 3941
downloadFile "ubc-dedup-8r-053.tar" 3942
downloadFile "ubc-dedup-8r-054.tar" 3943
downloadFile "ubc-dedup-8r-055.tar" 3944
downloadFile "ubc-dedup-8r-056.tar" 3945
downloadFile "ubc-dedup-8r-057.tar" 3946
downloadFile "ubc-dedup-8r-058.tar" 3947
downloadFile "ubc-dedup-8r-059.tar" 3948
downloadFile "ubc-dedup-8r-060.tar" 3949
downloadFile "ubc-dedup-8r-061.tar" 3950
downloadFile "ubc-dedup-8r-062.tar" 3951
downloadFile "ubc-dedup-8r-063.tar" 3952
downloadFile "ubc-dedup-8r-064.tar" 3953
downloadFile "ubc-dedup-8r-065.tar" 3954
downloadFile "ubc-dedup-8r-066.tar" 3955
downloadFile "ubc-dedup-8r-067.tar" 3956
downloadFile "ubc-dedup-8r-068.tar" 3957
downloadFile "ubc-dedup-8r-069.tar" 3958
downloadFile "ubc-dedup-8r-070.tar" 3959
downloadFile "ubc-dedup-8r-071.tar" 3960
downloadFile "ubc-dedup-8r-072.tar" 3961
downloadFile "ubc-dedup-8r-073.tar" 3962
downloadFile "ubc-dedup-8r-074.tar" 3963
downloadFile "ubc-dedup-8r-075.tar" 3964
downloadFile "ubc-dedup-8r-076.tar" 3965
downloadFile "ubc-dedup-8r-077.tar" 3966
downloadFile "ubc-dedup-8r-078.tar" 3967
downloadFile "ubc-dedup-8r-079.tar" 3968
downloadFile "ubc-dedup-8r-080.tar" 3969
downloadFile "ubc-dedup-8r-081.tar" 3970
downloadFile "ubc-dedup-8r-082.tar" 3971
downloadFile "ubc-dedup-8r-083.tar" 3972
downloadFile "ubc-dedup-8r-084.tar" 3973
downloadFile "ubc-dedup-8r-085.tar" 3974
downloadFile "ubc-dedup-8r-086.tar" 3975
downloadFile "ubc-dedup-8r-087.tar" 3976
downloadFile "ubc-dedup-8r-088.tar" 3977
downloadFile "ubc-dedup-8r-089.tar" 3978
downloadFile "ubc-dedup-8r-090.tar" 3979
downloadFile "ubc-dedup-8r-091.tar" 3980
downloadFile "ubc-dedup-8r-092.tar" 3981
downloadFile "ubc-dedup-8r-093.tar" 3982
downloadFile "ubc-dedup-8r-094.tar" 3983
downloadFile "ubc-dedup-8r-095.tar" 3984
downloadFile "ubc-dedup-8r-096.tar" 3985
downloadFile "ubc-dedup-8r-097.tar" 3986
downloadFile "ubc-dedup-8r-098.tar" 3987
downloadFile "ubc-dedup-8r-099.tar" 3988
downloadFile "ubc-dedup-8r-100.tar" 3989
downloadFile "ubc-dedup-8r-101.tar" 3990
downloadFile "ubc-dedup-8r-102.tar" 3991
downloadFile "ubc-dedup-8r-103.tar" 3992
downloadFile "ubc-dedup-8r-104.tar" 3993
downloadFile "ubc-dedup-8r-105.tar" 3994
downloadFile "ubc-dedup-8r-106.tar" 3995
downloadFile "ubc-dedup-8r-107.tar" 3996
downloadFile "ubc-dedup-8r-108.tar" 3997
downloadFile "ubc-dedup-8r-109.tar" 3998
downloadFile "ubc-dedup-8r-110.tar" 3999
downloadFile "ubc-dedup-8r-111.tar" 4000
downloadFile "ubc-dedup-8r-112.tar" 4001
downloadFile "ubc-dedup-8r-113.tar" 4002
downloadFile "ubc-dedup-8r-114.tar" 4003
downloadFile "ubc-dedup-8r-115.tar" 4004
downloadFile "ubc-dedup-8r-116.tar" 4005
downloadFile "ubc-dedup-8r-117.tar" 4006
downloadFile "ubc-dedup-8r-118.tar" 4007
downloadFile "ubc-dedup-8r-119.tar" 4008
downloadFile "ubc-dedup-8r-120.tar" 4009
downloadFile "ubc-dedup-8r-121.tar" 4010
downloadFile "ubc-dedup-8r-122.tar" 4011
downloadFile "ubc-dedup-8r-123.tar" 4012
downloadFile "ubc-dedup-8r-124.tar" 4013
downloadFile "ubc-dedup-8r-125.tar" 4014
downloadFile "ubc-dedup-8r-126.tar" 4015
downloadFile "ubc-dedup-8r-127.tar" 4016
downloadFile "ubc-dedup-8r-128.tar" 4017
downloadFile "ubc-dedup-8r-129.tar" 4018
downloadFile "ubc-dedup-8r-130.tar" 4019
downloadFile "ubc-dedup-8r-131.tar" 4020
downloadFile "ubc-dedup-8r-132.tar" 4021
downloadFile "ubc-dedup-8r-133.tar" 4022
downloadFile "ubc-dedup-8r-134.tar" 4023
downloadFile "ubc-dedup-8r-135.tar" 4024
downloadFile "ubc-dedup-8r-136.tar" 4025
downloadFile "ubc-dedup-8r-137.tar" 4026
downloadFile "ubc-dedup-8r-138.tar" 4027
downloadFile "ubc-dedup-8r-139.tar" 4028
downloadFile "ubc-dedup-8r-140.tar" 4029
downloadFile "ubc-dedup-8r-141.tar" 4030
downloadFile "ubc-dedup-8r-142.tar" 4031
downloadFile "ubc-dedup-8r-143.tar" 4032
downloadFile "ubc-dedup-8r-144.tar" 4033
downloadFile "ubc-dedup-8r-145.tar" 4034
downloadFile "ubc-dedup-8r-146.tar" 4035
downloadFile "ubc-dedup-8r-147.tar" 4036
downloadFile "ubc-dedup-8r-148.tar" 4037
downloadFile "ubc-dedup-8r-149.tar" 4038
downloadFile "ubc-dedup-8r-150.tar" 4039
downloadFile "ubc-dedup-8r-151.tar" 4040
downloadFile "ubc-dedup-8r-152.tar" 4041

echo "Finished All Downloads"
rm -f $cookies
